### ISSUE TITLE
Cell selection upon on tap or click

### ISSUE THREAD

**Issue by Harsha-M** [zhangbozhb/Carousel#1]
Thanks for this awesome Carousel. I have a question.
How do we detect if a cell has been tapped or clicked? Is there any delegate method for it? 

Thanks in advance!

**Comment by Harsha-M** [comment]
Pls repond.. my release is depend on this!! Thanks

**Comment by zhangbozhb** [comment]
@Harsha-M I'm sorry to reply you so late.  "How do we detect if a cell has been tapped or clicked? Is there any delegate method for it?" There is no delegate to handle tap or click event. However you can add tap gesture to your cells, this will fix you question. Honestly speaking, this is not perfect way, it does work.
I add delegate methods to handle cell click/select events in next release(next few days). Thanks for your reply.

**Comment by Harsha-M** [comment]
Thanks @zhangbozhb for reply! Just want to let you know you did great job with this carousel!

**Comment by zhangbozhb** [comment]
@Harsha-M fix in release 1.1/0.7. I do recommend [iCarousel](https://github.com/nicklockwood/iCarousel) .
