### ISSUE TITLE
Support for Swift 4 / Xcode 9

### ISSUE THREAD

**Issue by danielRi** [zhangbozhb/Carousel#3]
Hi friend,

it seems like since Xcode 9 / Sift 4 I get this error on multiple lines:

`Argument of '#selector' refers to instance method 'autoScrollToNext()' that is not exposed to Objective-C`

Adding `@objc` annotation to the function fixes the issue. Will you update the cocoapod?

**Comment by zhangbozhb** [comment]
@danielRi  3ks. update to fix error in swift4 in version 1.5

**Comment by danielRi** [comment]
very nice, thank you for the quick fix!
